-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.conducting_courses
(
    conducting_course_id serial NOT NULL,
    course_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    capacity integer NOT NULL,
    CONSTRAINT conducting_courses_pkey PRIMARY KEY (conducting_course_id),
    CONSTRAINT conducting_courses_conducting_course_id_course_id_key UNIQUE (conducting_course_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.courses
(
    course_id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS public.record_course
(
    record_course_id serial NOT NULL,
    student_id integer NOT NULL,
    conducting_course_id integer NOT NULL,
    course_id integer NOT NULL,
    CONSTRAINT record_course_pkey PRIMARY KEY (record_course_id),
    CONSTRAINT record_course_student_id_conducting_course_id_key UNIQUE (student_id, conducting_course_id),
    CONSTRAINT record_course_student_id_course_id_key UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.students
(
    student_id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT students_pkey PRIMARY KEY (student_id)
);

ALTER TABLE IF EXISTS public.conducting_courses
    ADD CONSTRAINT conducting_courses_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_course
    ADD CONSTRAINT fk_conducting_course_course FOREIGN KEY (conducting_course_id, course_id)
    REFERENCES public.conducting_courses (conducting_course_id, course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.record_course
    ADD CONSTRAINT record_course_conducting_course_id_fkey FOREIGN KEY (conducting_course_id)
    REFERENCES public.conducting_courses (conducting_course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_record_course_conducting_course
    ON public.record_course(conducting_course_id);


ALTER TABLE IF EXISTS public.record_course
    ADD CONSTRAINT record_course_course_id_fkey FOREIGN KEY (course_id)
    REFERENCES public.courses (course_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.record_course
    ADD CONSTRAINT record_course_student_id_fkey FOREIGN KEY (student_id)
    REFERENCES public.students (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;